# Generated by Django 5.0.2 on 2024-03-05 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_task_assigned_to_task_time_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_estimate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 7, 54, 41, 79024)),
        ),
    ]
