# Generated by Django 5.0.2 on 2024-03-11 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_task_time_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_estimate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 12, 16, 46, 54, 630928), null=True),
        ),
    ]
