# Generated by Django 5.0.2 on 2024-04-10 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_task_time_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_estimate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 15, 29, 25, 166036), null=True),
        ),
    ]
